# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-21 03:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('namespace', models.CharField(default=b'locale', max_length=150)),
                ('description', models.TextField(blank=True, default=b'')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repository', to=settings.AUTH_USER_MODEL, verbose_name=b'owner')),
            ],
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('path', models.CharField(max_length=250)),
                ('readable', models.BooleanField(default=True)),
                ('private', models.BooleanField(default=True)),
                ('isfile', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volume', to=settings.AUTH_USER_MODEL, verbose_name=b'owner')),
            ],
        ),
    ]
