# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-21 04:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repository', models.CharField(max_length=250)),
                ('tag', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[(b'PU', b'pulling'), (b'BD', b'building'), (b'EX', b'existed'), (b'ER', b'error')], default=b'PU', max_length=2)),
                ('isbuild', models.BooleanField(default=False)),
                ('users', models.ManyToManyField(related_name='image', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='repository',
            unique_together=set([('name', 'namespace')]),
        ),
        migrations.AlterUniqueTogether(
            name='image',
            unique_together=set([('repository', 'tag')]),
        ),
    ]
