# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-21 06:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_auto_20160521_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(default=b'/', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('command', models.CharField(blank=True, default=b'', max_length=150)),
                ('restart', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Creation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=b'', max_length=150)),
                ('value', models.CharField(default=b'', max_length=150)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environments', to='api.Container')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=150)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='api.Container')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='api.Container')),
            ],
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.IntegerField()),
                ('external', models.BooleanField(default=False)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='api.Container')),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(default=b'000000000000', max_length=12)),
                ('status', models.CharField(blank=True, max_length=100)),
                ('detail', models.TextField(blank=True, default=b'')),
                ('pr', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='image',
            name='users',
            field=models.ManyToManyField(related_name='images', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='repository',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to=settings.AUTH_USER_MODEL, verbose_name=b'owner'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to=settings.AUTH_USER_MODEL, verbose_name=b'owner'),
        ),
        migrations.AddField(
            model_name='process',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', related_query_name=b'process', to='api.Image'),
        ),
        migrations.AddField(
            model_name='container',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='api.Image'),
        ),
        migrations.AddField(
            model_name='container',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='containers', to=settings.AUTH_USER_MODEL, verbose_name=b'owner'),
        ),
        migrations.AddField(
            model_name='bind',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='binds', to='api.Container'),
        ),
        migrations.AddField(
            model_name='bind',
            name='volume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='binds', to='api.Volume'),
        ),
        migrations.AlterUniqueTogether(
            name='process',
            unique_together=set([('pid', 'image')]),
        ),
        migrations.AlterUniqueTogether(
            name='creation',
            unique_together=set([('user', 'date')]),
        ),
        migrations.AlterUniqueTogether(
            name='bind',
            unique_together=set([('container', 'path')]),
        ),
    ]
