# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-21 06:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20160521_1412'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='environment',
            unique_together=set([('container', 'key')]),
        ),
        migrations.AlterUniqueTogether(
            name='link',
            unique_together=set([('container', 'alias')]),
        ),
        migrations.AlterUniqueTogether(
            name='port',
            unique_together=set([('container', 'port')]),
        ),
    ]
